--LOCATION
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, COUNTRY, REGION, CITY, LATITUDE, LONGITUDE) VALUES (1, '코드 스쿼드', '한국', '서울시', '강남구', 0, 0);

--OPTION
INSERT INTO ACCOMODATION_OPTION (OPTION_ID, BATH_ROOM_COUNT, BED_ROOM_COUNT, BED_COUNT) VALUES (1, 1, 1, 1);

--ACCOMODATION
INSERT INTO ACCOMODATION(ACCOMODATION_ID, LOCATION_ID, HOST_NAME, DISCRIPTION, ACCOMODATION_TYPE, MINIMUM_OCCUPANCY, MAXIMUM_OCCUPANCY, AVERAGE_POINT, OPTION_ID)
VALUES (1, 1, 'cooper', 'nice location', '주택', 2, 4, 3.0, 1);

--IMAGE
INSERT INTO IMAGE (IMAGE_ID, ACCOMODATION_ID, IMAGE_URL) VALUES (1, 1, 'https://images.adsttc.com/media/images/5ecd/d4ac/b357/65c6/7300/009d/slideshow/02C.jpg?1590547607');
